### ISSUE TITLE
/crazyflie/gazebo/command/motor_speed topic don't seem

### ISSUE THREAD

**Issue by omr-web** [bitcraze/crazyflie-simulation#32]
I run crazyflie_world.sdf but I dont see /crazyflie/gazebo/command/motor_speed topic so, when I write  ign topic -t /crazyflie/gazebo/command/motor_speed --msgtype ignition.msgs.Actuators -p 'velocity:[2500,2500,2500,2500]' , nothing happend.

**Comment by omr-web** [comment]
I use gazebo ignition garden, I solved the problem. I had to start the gazebo with the -r parameter

**Comment by knmcguire** [comment]
Great, then I'll close the issue

**Comment by omr-web** [comment]
I wanted to subscribe to a topic that came with the ros2 bridge to the plugin code you wrote. How can I do that? How can I subscribe to a topic from Ros Bridge in an ignition gazebo?

**Comment by knmcguire** [comment]
The solution of the last comment is in https://github.com/bitcraze/crazyflie-simulation/issues/33
