### ISSUE TITLE
Subscribe to the ROS2 topic in ignition gazebo

### ISSUE THREAD

**Issue by omr-web** [bitcraze/crazyflie-simulation#33]
I am using ROS2 Humble. I want to subscribe to a float type message published with ROS2 in the ignition gazebo plugin.
Using ROS2 bridge I can see the float type message by typing ign topic -l command. But I cannot subscribe using the node->Subscribe function in the transport library. In summary, how can I subscribe to the ros2 topic on ignition gazebo?

Thank you your help.

**Comment by omr-web** [comment]
I  use transport 11 instead 12 then I solved it.

**Comment by knmcguire** [comment]
Thanks for the update! We haven't looked at the gazebo simulation for a while but it is good to know it works.
