### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by hanselliyj** [bitcraze/crazyflie-simulation#45]
HI,

I am trying to  simulate the webot examples but have issues with the pid_controller.

I got this message on webot:

 File "crazyflie_controller_py.py", line 30, in <module>
    from pid_controller import pid_velocity_fixed_height_controller
ImportError: cannot import name 'pid_velocity_fixed_height_controller' from 'pid_controller' (/home/crazyfyp/.local/lib/python3.8/site-packages/pid_controller/__init__.py)
WARNING: 'crazyflie_controller_py' controller exited with status: 1.

**Comment by knmcguire** [comment]
Let me just reopen this one! there were some renaming issues in the last merge. It should be fixed now if you get the latest version of the repository.

Could you let us know if this fixed it for you?

**Comment by hanselliyj** [comment]
Hi @knmcguire! I managed to fix the issue. I made an error when copying the path... rookie mistake
