### ISSUE TITLE
Gazebo simulation broken paths

### ISSUE THREAD

**Issue by AntrikshMehta** [bitcraze/crazyflie-simulation#50]
hey there!
I wanted to simulate crazyflie using gazebo( using WSL ) and followed the instructions given.  I encountered a few problems and tried to fix them myself.

first I followed the mentioned steps which were :
            export IGN_GAZEBO_RESOURCE_PATH="path/to/crazyflie-simulation/gazebo-ignition/"
            gz sim crazyflie_world.sdf 
I faced the issue "Unable to find or download file"

I tried changing the path and instead used:
            export GZ_SIM_RESOURCE_PATH="/root/crazyflie_simulation/simulator_files/gazebo/worlds" (path in my system)
            gz sim crazyflie_world.sdf

this solved the problem and loaded the world, but still the crazyflie model wasn't loading in the world.
I got an error in the terminal:
[GUI] [Err] [SystemPaths.cc:534] File [/root/crazyflie_simulation/simulator_files/meshes/collada_files/cf2_assembly.dae] resolved to path [/root/crazyflie_simulation/simulator_files/meshes/collada_files/cf2_assembly.dae] but the path does not exist 

so in order to resolve it, I moved the meshes folder inside the simulator_files directory.

This solved the issue and my model was also loading correctly.

Next, I wanted to run the motors, so i followed the steps and ran the following command while the model was running in the terminal, but it had no effect on the model:
gz topic -t /crazyflie/gazebo/command/motor_speed --msgtype ignition.msgs.Actuators -p 'velocity:[250,250,250,250]'

Can you please guide me and point out what I'm doing wrong. Also, if you could please point out further scope in simulation, it would be really helpful.

(P.S : I'm new to drones and ubuntu os too & I'm  trying to learn things along the way :') )

**Comment by knmcguire** [comment]
Ahh.... that could be. I've changed the folder structure quite a bit but perhaps the gazebo one is not as finished as it should. I did that in this PR so perhaps you can change the folder structure itself until I find time to fix it? This is the PR in question https://github.com/bitcraze/crazyflie-simulation/pull/44

If you are a beginner, why don't you try the getting started tutorial? It's with webots but it is more beginner friendly I would say.

- https://www.bitcraze.io/documentation/tutorials/getting-started-with-simulation/
- Developer meeting about it: https://www.bitcraze.io/documentation/tutorials/getting-started-with-simulation/

**Comment by knmcguire** [comment]
The path needs to be replaced with the actual path to the simulator.

About the gz command not existing, I'll try to figure that out as soon as possible

**Comment by knmcguire** [comment]
So there have been some fixes implemented in this PR: https://github.com/bitcraze/crazyflie-simulation/pull/56. The gz topic for the motor commands does exist, so there is no problem there. But there is something else going on, namely that the props don't respond on the command so I'll make another issue for that. 

Since this crazyflie gazebo model and functionality is highly experimental, I do recommend you to look at other solutions, like webots or to look at the [aerostack2](https://github.com/aerostack2/aerostack2/) project who use the same model in their autonomy stack for gazebo.
