### ISSUE TITLE
webots crash

### ISSUE THREAD

**Issue by anadiedrichs** [bitcraze/crazyflie-simulation#58]
Hi! I started with Crazyflie simulation in Webots a few months ago.

I want to use it to experiment with Crazyflie quadcopter and reinforcement learning. Crazyflie should take off initially, and then I would consider the following actions. 

I'm having some issues with the simulator because it crashes after the drone takes off. I made a video showing the behavior (https://github.com/anadiedrichs/drone-deep-rl/tree/main/1_crazyflie/controllers/v2_openaigym_stablebaselines/README.md )

My controller code: https://github.com/anadiedrichs/drone-deep-rl/blob/main/1_crazyflie/controllers/v2_openaigym_stablebaselines/v2_openaigym_stablebaselines.py

Any suggestions?

**Comment by anadiedrichs** [comment]
It could be a Webots bug, so I upload an issue https://github.com/cyberbotics/webots/issues/6539

**Comment by gemenerik** [comment]
Hi Ana! That indeed seems like a Webots bug, I'll close this for now but don't hesitate to reopen if required.
