### ISSUE TITLE
Creating a discussion section

### ISSUE THREAD

**Issue by gsilano** [bitcraze/crazyflie-simulation#7]
Hi Kimberly! Nice idea and great work. Well done, girl!! I was wondering if you were considering creating a discussion section in this repisotory. I have some references that may be useful to you and others member of the community. What do you think?

**Comment by knmcguire** [comment]
Hi! That would be great actually! I think the community (and us) would really benefit from your insights.

Actually I was thinking about the same thing about the discussion tab! But the problem now is... where to have these discussions? We currently have our [forum](https://forum.bitcraze.io/) which we usually like to use for support and discussions, but the Github integration is not great.. 

And also we have a gazillion repositories so it would be unwise for us to start an discussion tab on each repository, so if we do it we should probably only do it in one, and most probably the crazyflie-firmware repo. 

on the other hand, we currently have the simulation [discussion thread](https://github.com/IMRCLab/crazyswarm2/discussions/3) on the Crazyswarm2 repository, which is starting to grow a bit out of proportion :sweat_smile: 

So still some unknowns but I'll discuss it today internally with the rest, so I'll update you about this!

**Comment by knmcguire** [comment]
@gsilano We still need to decide internally what our strategy is for discussions and our old forum, but the rest agreed if I just start the discussion tab only on this repository, to try it out and see if we like it as a possible replacement. 

So let's discuss there!

**Comment by knmcguire** [comment]
btw, we are moving to organization discussions now for github. So I'll close the discussion section on this repo and transfer all discussions to here: https://github.com/orgs/bitcraze/discussions

For simulations, use the label simulation.
