### ISSUE TITLE
Which version of Gazebo Ignition is currently in use?

### ISSUE THREAD

**Issue by Combuster54** [bitcraze/crazyflie-simulation#71]
Hi. I was trying to run the Gazebo user guide by following the documentation, but I'm seeing some inconsistencies.

- The Gazebo tutorial tells how to install Gazebo Fortress, but when I want to try the examples, the commands use gz sim, which could be Gazebo Garden or Harmonic. So what version is it?

**Comment by Bananazooka** [comment]
Hi, 
thanks for pointing out this discrepancy. You should try Gazebo Harmonic - our latest [tutorial ](https://www.bitcraze.io/2024/09/crazyflies-adventures-with-ros-2-and-gazebo/)points to that.

**Comment by gemenerik** [comment]
Hi Ruben. To the best of my knowledge, we don’t have any resources for reinforcement learning with Gazebo Harmonic. However, it’s possible that others have explored using the Crazyflie in a similar context. Alternatively, you might find general resources online for reinforcement learning with UAVs in Gazebo that could be applicable to the Crazyflie.

**Comment by Combuster54** [comment]
Thanks for your advice @gemenerik. I'm going to research it.
